### ISSUE TITLE
fix issue in regional aggregate download - 0 observations 

### ISSUE THREAD

**Issue by davidn10** [worldbank/povcalnet#12]
. povcalnet, region(SSA) year(all) aggregate clear

 Query at $1.9 poverty line
--------------------------------------------------------------------------------------------------
Year:              YearSelected=all
Country:           Countries=AGO_3,BDI_3,BEN_3,BFA_3,BWA_3,CAF_3,CIV_3,CMR_3,COD_3,COG_3,COM_3,CPV
> _3,ETH_1,ETH_3,GAB_3,GHA_3,GIN_3,GMB_3,GNB_3,KEN_3,LBR_3,LSO_3,MDG_3,MLI_3,MOZ_3,MRT_3,MUS_3,MWI
> _3,NAM_3,NER_3,NGA_3,RWA_3,SDN_3,SEN_3,SLE_3,SSD_3,STP_3,SWZ_3,SYC_3,TCD_3,TGO_3,TZA_3,UGA_3,ZAF
> _3,ZMB_3,ZWE_3
Poverty line:      PovertyLine=1.9
Aggregation:       &display=R
PPP:               
--------------------
No. Obs:           0
--------------------------------------------------------------------------------------------------

**Comment by randrescastaneda** [comment]
Dear David, 

Issue solved.  Please update your file following [these instructions](https://github.com/worldbank/povcalnet#temporal-installation)

Best,
