### ISSUE TITLE
Using cl subcommand with the same country appearing multiple times

### ISSUE THREAD

**Issue by danielmahler** [worldbank/povcalnet#13]
Hi Andres and colleagues,

I am having an issue with the cl suboption I haven't been able to solve. 
The two examples below help illustrate my problem:

Example A:
```stata
local coun ALB AGO
local year 2008 2000 
local plin 1.9 1.8 
local cove national national 
povcalnet cl, country(`coun') year(`year') povline(`plin') coverage(`cove') clear 
```

Example B: 

```stata
local coun ALB AGO AGO
local year 2008 2000 2008
local plin 1.9 1.8 1.7
local cove national national national
povcalnet cl, country(`coun') year(`year') povline(`plin') coverage(`cove') clear
```

On my end, example A works while example B returns an error.
Is there a way I can get the information I am trying to get in example B with only one line of povcalnet cl?

Many thanks,
Daniel

**Comment by randrescastaneda** [comment]
HI Daniel, 

The issue has been solved. Please, download the package again following the instructions below. 

1. Click on the green icon "Clone or Download" above. 
2. Download the package as zip. 
3. Extract the files with extension `.ado` and `.sthlp` only, and place them in the directory `c:/ado/plus/p`
4. type `discard` in Stata. 

Please, test the command an let us know whether it is working properly. 

Best,

**Comment by danielmahler** [comment]
It works perfectly, many thanks for your quick response, Andres!

Best,
Daniel
