### ISSUE TITLE
Limit to simultaneous queries with cl subcommand

### ISSUE THREAD

**Issue by danielmahler** [worldbank/povcalnet#14]
Hi Andres and team,

When using the cl subcommand there seems to be a limit of ten one-on-one queries that can be done simultaneously. Is that correct? If so, is it feasible to have this limit raised?

Many thanks for your help as always.

Best,
Daniel

**Comment by randrescastaneda** [comment]
Hi Daniel,

Could you please send us an example of the limit?  It is likely that the limit is in the API. Yet, let us test and confirm.

Thanks.
Best,
----------------------
R.Andrés Castañeda

**Comment by danielmahler** [comment]
Of course, my apologies, Andres.
Here are two examples. Example A works on my end while Example B does not.

Best,
Daniel

Example A:
povcalnet cl, country(ALB ALB ALB ALB ALB ALB ALB ALB ALB ALB) ///
year(2008 2008 2008 2008 2008 2008 2008 2008 2008 2008) ///
povline(1 2 3 4 5 6 7 8 9 10) ///
coverage(national national national national national national national national national national) clear 

Example B:
povcalnet cl, country(ALB ALB ALB ALB ALB ALB ALB ALB ALB ALB ALB) ///
year(2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008) ///
povline(1 2 3 4 5 6 7 8 9 10 11) ///
coverage(national national national national national national national national national national national) clear

**Comment by tonyfujs** [comment]
@danielmahler @randrescastaneda Just confirming this is not an API limitation. This endpoint (example B) works as expected:
http://iresearch.worldbank.org/povcalnet/povcalnetapi.ashx?C0=ALB_3&PL0=1&Y0=2008&C1=ALB_3&PL1=2&Y1=2008&C2=ALB_3&PL2=3&Y2=2008&C3=ALB_3&PL3=4&Y3=2008&C4=ALB_3&PL4=5&Y4=2008&C5=ALB_3&PL5=6&Y5=2008&C6=ALB_3&PL6=7&Y6=2008&C7=ALB_3&PL7=8&Y7=2008&C8=ALB_3&PL8=9&Y8=2008&C9=ALB_3&PL9=10&Y9=2008&C10=ALB_3&PL10=11&Y10=2008&format=csv

**Comment by randrescastaneda** [comment]
Thank you, Tony and Daniel. 

The issue has been fixed. 

Best,

**Comment by danielmahler** [comment]
Many thanks to both of you for your quick fixes! :)
