### ISSUE TITLE
regarding stata povcal with alternative PPP

### ISSUE THREAD

**Issue by SriramShankar777** [worldbank/povcalnet#17]
I am trying to use stata povcal with my own PPP.

For example, for Armenia (ARM) first I use WB’s default PPP (183.7796) using the command: povcalnet, country(ARM) year(2011) coverage(national)   clear

And then I use alternative PPP (175.339) using command: povcalnet, country(ARM) year(2011) ppp(175.339) coverage(national)   clear

The results from alternative PPP is the exactly identical to the output for default PPP.

Am I doing something wrong. I expected a different headcount due to change in the Armenian PPP. Your comments/suggestions regarding this will be much appreciated.

**Comment by randrescastaneda** [comment]
@davidlvargas , 

Could you please take a look at this?

Thanks. 
Best,

**Comment by davidlvargas** [comment]
@randrescastaneda, 

Seems to be a minor issue on the povcalnet ado. Already solved, I started a pull request from a new branch "ppp_solve" addressing this. Please check it out and let me know if other adjustments are needed or advised.

Thanks, 
David

**Comment by randrescastaneda** [comment]
Thak you @davidlvargas. As always, very efficient. 

@SriramShankar777 , the issue has been solved and it is available in the master branch. 

Best,

**Comment by SriramShankar777** [comment]
Is this issue resolved in the latest povcal command?

Thanks,
Sriram

**Comment by randrescastaneda** [comment]
@SriramShankar777 , 
As I said [above](https://github.com/worldbank/povcalnet/issues/17#issuecomment-656303211), this issue is already solved and you can find it in the master branch. It is not yet available in SSC. 

Best,
