### ISSUE TITLE
Check version in Github

### ISSUE THREAD

**Issue by randrescastaneda** [worldbank/povcalnet#21]
Hola @davidlvargas , 

Could you please modify these [lines](https://github.com/worldbank/povcalnet/blob/e52644473912497b48dc08f48b48fbd8d78d511d/povcalnet.ado#L86-L110) to make sure that the condition in line [110](https://github.com/worldbank/povcalnet/blob/e52644473912497b48dc08f48b48fbd8d78d511d/povcalnet.ado#L110) reads `<` instead of `:=` ? You may need to convert the [semantic versioning](https://semver.org/) of Github releases into real numbers. 

Please, let me know if you have any doubt. 

Thanks.

**Comment by davidlvargas** [comment]
Hola @randrescastaneda,

I opened a pull request regarding this. Please let me know if changes are needed.

Thanks,
David.

**Comment by randrescastaneda** [comment]
perfect. Thanks.
